'use strict';

// ⚠️ SECURITY: this file embeds the client private key + tls-crypt key for the
// self-hosted AWS OpenVPN server. Anyone with this file can connect to that
// server. Keep this repository private. To rotate, run setup-vps-openvpn.sh
// again on the VPS and replace the cert/key blocks below with the new
// nx3vpn-client.ovpn it prints.
//
// This is the baked-in DEFAULT primary US server (34.225.239.148), generated by
// scripts/setup-vps-openvpn.sh — Easy-RSA CA, ECDSA certs, tls-crypt, AES-256-GCM
// (the same consistent setup as the working second server). The app connects to
// it immediately without fetching any public list. It can be overridden at
// runtime by CUSTOM_OVPN or ~/.nx3vpn/custom-server.ovpn (see customServer.js).

const DEFAULT_SERVER_OVPN = `client
dev tun
proto udp
remote 34.225.239.148 1194
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
cipher AES-256-GCM
data-ciphers AES-256-GCM:AES-128-GCM
auth SHA256
verb 3
<ca>
-----BEGIN CERTIFICATE-----
MIIBvzCCAWWgAwIBAgIUdk4ieoNXYCW4ex0njyXECT1t+HAwCgYIKoZIzj0EAwIw
FjEUMBIGA1UEAwwLRWFzeS1SU0EgQ0EwHhcNMjYwNjI2MTc0NzQ3WhcNMzYwNjIz
MTc0NzQ3WjAWMRQwEgYDVQQDDAtFYXN5LVJTQSBDQTBZMBMGByqGSM49AgEGCCqG
SM49AwEHA0IABMGQR1Huak1C8ofya57xM7H47ucHgKOHA02dKe9ldjGFRU9tIIOP
+xay4XkPOJaD7JKNKTFnB9Su4SjLVOQHR4KjgZAwgY0wDAYDVR0TBAUwAwEB/zAd
BgNVHQ4EFgQUvjxkt12Bb/5UP19cUDqxPRCG5OMwUQYDVR0jBEowSIAUvjxkt12B
b/5UP19cUDqxPRCG5OOhGqQYMBYxFDASBgNVBAMMC0Vhc3ktUlNBIENBghR2TiJ6
g1dgJbh7HSePJcQJPW34cDALBgNVHQ8EBAMCAQYwCgYIKoZIzj0EAwIDSAAwRQIh
AJiYh7l7HKOKylGDNn3f7Y7vOwxIvd3Zo8I2rHu3ONSyAiBU8u7z9cVSyTGI0iMQ
Q3H0uTosz+p8C1IHoQKIwKnu+Q==
-----END CERTIFICATE-----
</ca>
<cert>
-----BEGIN CERTIFICATE-----
MIIByjCCAW+gAwIBAgIRAOOKy7qyyOqeuJiMM/R+YDowCgYIKoZIzj0EAwIwFjEU
MBIGA1UEAwwLRWFzeS1SU0EgQ0EwHhcNMjYwNjI2MTc0NzQ3WhcNMjgwOTI4MTc0
NzQ3WjARMQ8wDQYDVQQDDAZjbGllbnQwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNC
AATp5gIQuWvI2dExYvyc8yX3h1iCZQ8sk+o6uaPvRX7Z2Fxw60qUEwbko+KnSf4j
J1kwzEgbfX4+nPwOA/JCInTro4GiMIGfMAkGA1UdEwQCMAAwHQYDVR0OBBYEFIC9
iWX3mmZz6wcYd+inoE+NoVFCMFEGA1UdIwRKMEiAFL48ZLddgW/+VD9fXFA6sT0Q
huTjoRqkGDAWMRQwEgYDVQQDDAtFYXN5LVJTQSBDQYIUdk4ieoNXYCW4ex0njyXE
CT1t+HAwEwYDVR0lBAwwCgYIKwYBBQUHAwIwCwYDVR0PBAQDAgeAMAoGCCqGSM49
BAMCA0kAMEYCIQDb9oR/tRTERuscmeqbAT2d0GSncE1Vpp0svwUz9aRqKQIhAIoO
4RE2y+T//zRPBXCXicFTFXtq9rMb0EIyjEPpUkGp
-----END CERTIFICATE-----
</cert>
<key>
-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgcoVsDH53hZbRJRmo
tu9Ecf6XW7E1GE9lwEEWotMAnmShRANCAATp5gIQuWvI2dExYvyc8yX3h1iCZQ8s
k+o6uaPvRX7Z2Fxw60qUEwbko+KnSf4jJ1kwzEgbfX4+nPwOA/JCInTr
-----END PRIVATE KEY-----
</key>
<tls-crypt>
#
# 2048 bit OpenVPN static key
#
-----BEGIN OpenVPN Static key V1-----
31fcc0dd45aad1e905f7da6b86894574
bd729b5bc009fbe1fba762f51452b105
6092adf53c62de91e71b29e12906c964
ab691e1ef66229d95b482fc7b80c09a6
0aa36550cdec8e4ee5eecff3b80fd45a
e7c4012bbe408ec86a2e0049c1ec336a
61526df8b0857722ec18a3f33ef9ce58
9533185ab950a7a4370d3624f602803e
31b3e784b365c3cf65bab1a15cef38be
dcd8747356d065fcc720303b8346c0b6
c1b5ed6cf53f6d91ace07bfab36080b4
cc9b73688da7a7735d0c1eaa8fea5093
adb25c34e79f2d482f6dd8d1c2ef3455
37f6245c666c47a77fefa99f4a71acd0
4705697d1c10bed6569badc7d90f497c
75fc6c3994c95ef0fab0f43aed35ecad
-----END OpenVPN Static key V1-----
</tls-crypt>
`;

module.exports = { DEFAULT_SERVER_OVPN };
